export const VOTE_REQUEST = "VOTE_REQUEST";
export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAIL = "VOTE_FAIL";
export const VOTE_RESET = "VOTE_RESET";

export const PROPOSE_REQUEST = "PROPOSE_REQUEST";
export const PROPOSE_SUCCESS = "PROPOSE_SUCCESS";
export const PROPOSE_FAIL = "PROPOSE_FAIL";
export const PROPOSE_RESET = "PROPOSE_RESET";
